### ISSUE TITLE
Request to Add Precautionary Note and gitignore file

### ISSUE THREAD

**Issue by hougangdev** [dannweeeee/wallet-maker#1]
## Issue 
I noticed that the project lacks a word of precation regarding the secure storage of private keys in the README file. Additionally, I think it would be beneficial to include a .gitignore file to prevent sensitive files, such as CSV files containing private keys from being pushed to the repository.

## Suggested changes
- Add a precautionary note to readme file about secure storing of private keys
- Include gitignore file to prevent the csv file with private keys from being pushed

**Comment by dannxbt** [comment]
good suggestion! i have made the neccessary fixes
